### ISSUE TITLE
Feature: Soft Remove

### ISSUE THREAD

**Issue by AllDayAlone** [paralect/node-mongo#21]
1. Add option `{ soft: bool }` (default `false`) to the createService options which opts on the feature
2. On `remove` document makes update `{ deletedOn: new Date() }` 
3. Add function `restore` which makes update `{ $unset: { deletedOn: "" } }`
4. Add option `{ soft: bool }` (default `true`) to all query methods which adds `{ deletedOn: { $exists: false } }` to the query

To discuss:
- Emit event `restored` and adjust event `removed`

**Comment by hovoodd** [comment]
I think we shouldn't add application specific logic to library.
Especially since you can define custom [service methods](API.md#setservicemethod) and use them instead of usual methods:

```js
// db.js

db.setServiceMethod('softRemove', (service, query) => {
  return service.atomic.update(
    query,
    { $set: { deletedOn: new Date() } },
    { multi: true },
  );
});
db.setServiceMethod('softRestore', (service, query) => {
  return service.atomic.update(
    query,
    { $unset: { deletedOn: '' } },
    { multi: true },
  );
});
db.setServiceMethod('softFind', (service, query) => {
  return service.find({ ...query, deletedOn: { $exists: false } });
});
```
