### ISSUE TITLE
createdOn/updatedOn rewrite

### ISSUE THREAD

**Issue by NesterenkoNikita** [paralect/node-mongo#7]
I think, that node-mongo should not rewrite createdOn/updatedOn if they were specified

**Comment by anorsich** [comment]
@NesterenkoNikita I agree, this is magic which I put together a long time ago. @ezhivitsa what do you think?

**Comment by ezhivitsa** [comment]
@anorsich If someone already uses this logic, we can not just delete this logic. But we can add option to the MongoService to enable or disable these fields. By default, we can disable these fields.

**Comment by anorsich** [comment]
@ezhivitsa Just merged your PR, I think we can reply and close this issue!

**Comment by ezhivitsa** [comment]
@NesterenkoNikita requested changes was released in the version 1.0.0.
