### ISSUE TITLE
Multiple MongoDBService instances? 

### ISSUE THREAD

**Issue by kaz138** [paralect/node-mongo#9]
Hey, 

I'm trying to create multiple instances of MongoDBService (each under an instance to write / read from a different collection set). Right now I'm unable to get this to work. Does this framework support this use case? Thanks.

**Comment by ezhivitsa** [comment]
Hello, @kasulty,

Yes, this module allows you to create different instances  of the `MongoDBService` for each collection.
[Here](https://github.com/paralect/koa-api-starter/blob/master/src/resources/user/user.service.js) you can see an example of using service.

In your case you will do something like the following example:
```javascript
const usersService = db.createService('users-collection');
const usersReadService = db.createQueryService('users-collection');
// -------
const clientsService = db.createService('clients-collection');
const clientsReadService = db.createQueryService('clients-collection');
```

**Comment by kaz138** [comment]
Sorry never saw unread notification. This is helpful I'll close this issue now. Thanks for answering.
